# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AhUPnj7KJP2dsbX41tdB8zTu142556HA
"""

from keras.applications import mobilenet

model=mobilenet.MobileNet(include_top=True,weights='imagenet')

model.layers

from keras import backend as K

from keras.models import Sequential

import tensorflow as tf
gpuoptions = tf.compat.v1.GPUOptions(allow_growth=True)
session = tf.compat.v1.Session(config=tf.compat.v1.ConfigProto(gpu_options=gpuoptions))
K.set_session(session)
classifier = Sequential()

from keras.preprocessing import image
import tensorflow as tf
from tensorflow import Graph

img_height, img_width=224,224

with open('/imagenet_classes.json','r') as f:
  labelInfo=f.read()

import json

labelInfo=json.loads(labelInfo)

labelInfo

testimage='/1.jpg'

from tensorflow.keras.utils import img_to_array
img = tf.keras.utils.load_img(testimage, target_size=(img_height, img_width))
x = img_to_array(img)
x=x/255
x=x.reshape(1,img_height, img_width,3)

predi=model.predict(x)

predi

import numpy as np
np.argmax(predi[0])

labelInfo['292']

from keras_preprocessing.image import load_img

from keras_preprocessing.image import img_to_array
from tensorflow.keras.utils import img_to_array

from PIL import Image as Img
testimage='/8.jpg'
img = tf.keras.utils.load_img(testimage, target_size=(img_height, img_width))
x = img_to_array(img)
x=x/255
x=x.reshape(1,img_height, img_width,3)
# model_graph = tf.
# tf_session = modeScope['modelObj']['tf_session']
# with model_graph.as_default():
#     with tf_session.as_default():
#         modelToUse=modeScope['modelObj']['recoModelObj'].model
predi=model.predict(x)

import numpy as np
np.argmax(predi[0])

labelInfo['11']

model.save('MobileNetModelImagenet.h5')

import keras

from keras.models import load_model

load_model('MobileNetModelImagenet.h5')